### ISSUE TITLE
WandB doesn't work with DDP

### ISSUE THREAD

**Issue by ivan-chai** [catalyst-team/catalyst#1316]
## 🐛 Bug Report
I get the error while using WandbLogger with ddp enabled:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/runner.py", line 829, in _run_stage
    self._run_event("on_stage_start")
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/runner.py", line 784, in _run_event
    getattr(self, event)(self)
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/runner.py", line 687, in on_stage_start
    self.log_hparams(hparams=self.hparams, scope="stage")
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/runner.py", line 575, in log_hparams
    stage_key=self.stage_key,
  File "/usr/local/lib/python3.6/dist-packages/catalyst/loggers/wandb.py", line 171, in log_hparams
    self.run.config.update(hparams)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_run.py", line 471, in config
    return self._config
AttributeError: 'Run' object has no attribute '_config'
```

By now Wandb is initialized before fork in `__init__`. It might be the source of the problem.

### Environment
```bash
Catalyst version: 21.09
PyTorch version: 1.9.1+cu102
Is debug build: No
CUDA used to build PyTorch: 10.2
TensorFlow version: N/A
TensorBoard version: 2.6.0

OS: linux
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB

Nvidia driver version: 455.45.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] catalyst==21.9
[pip3] numpy==1.19.5
[pip3] tensorboard==2.6.0
[pip3] tensorboard-data-server==0.6.1
[pip3] tensorboard-plugin-wit==1.8.0
[pip3] tensorboardX==2.2
[pip3] torch==1.9.1
[pip3] torchvision==0.10.1
[conda] Could not collect
```

**Comment by Scitator** [comment]
🤔  not sure if,
@AyushExel could you please help with the Wandb?
looks like there were some changes with 
```bash
File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_run.py", line 471, in config
    return self._config
```

**Comment by Scitator** [comment]
meanwhile, @ivan-chai does the error occurs only during DDP runs?
PS. cause there are now difference in logging honestly 😂

**Comment by AyushExel** [comment]
@Scitator thanks for bringing this up. I'll take a look today. Was this working in older version of wandb?

**Comment by ivan-chai** [comment]
The problem is only within DDP setup. I didn't try previous versions of wandb.

**Comment by Scitator** [comment]
🤔  @ivan-chai is there any minimal example to reproduce?
something like https://github.com/catalyst-team/catalyst/tree/master/examples/engines with wandb maybe?

**Comment by AyushExel** [comment]
That would be very helpful. Thanks

**Comment by Scitator** [comment]
@ivan-chai 👀 has the bug been fixed?

**Comment by Scitator** [comment]
@ivan-chai 👀

**Comment by AyushExel** [comment]
@Scitator @ivan-chai I haven't pushed any DDP-related fix. So if it is solved, it wasn't me. @ivan-chai can you please provide a minimal example to repro?

**Comment by foolsholder** [comment]
Hello, I have some thoughts how to fix it. 

It's described here 
https://docs.wandb.ai/guides/track/advanced/distributed-training 
and here 
https://github.com/wandb/examples/tree/master/examples/pytorch/pytorch-ddp#method-1-log-from-a-single-process, 
that if you want to use WandB with DistributedDataParallel and gather information from all gpus, you need to initialize wandb with group='DDP' parameter before calling torch.distributed.init_process_group.
```
run = wandb.init(
    entity=args.entity,
    project=args.project,
    group="DDP",
)
```
In WandbLogger we don't pass group parameter for DDP training. https://catalyst-team.github.io/catalyst/_modules/catalyst/loggers/wandb.html#WandbLogger
```
def __init__(
        self,
        project: str,
        name: Optional[str] = None,
        entity: Optional[str] = None,
        log_batch_metrics: bool = SETTINGS.log_batch_metrics,
        log_epoch_metrics: bool = SETTINGS.log_epoch_metrics,
    ) -> None:
        super().__init__(log_batch_metrics=log_batch_metrics, log_epoch_metrics=log_epoch_metrics)
        self.project = project
        self.name = name
        self.entity = entity
        self.run = wandb.init(
            project=self.project, name=self.name, entity=self.entity, allow_val_change=True
        )
```

However we need to start out python file like:
```
python -m torch.distributed.launch \
  --nproc_per_node <NUM_GPUS> \
  --nnodes 1 \
  --node_rank 0 \
  log-ddp.py \
    --epochs 10 \
    --batch 512 \
    --entity <ENTITY> \
    --project <PROJECT>
```

**Comment by foolsholder** [comment]
I suggest just passing "group" parameter to WandbLogger with the default value "None". 
You can see it in https://github.com/wandb/client/blob/5e019ad35ff9b41da73332340705e0fdcfdacabc/wandb/sdk/wandb_init.py#L702 .

So it will look something like this
```
def __init__(
        self,
        project: str,
        name: Optional[str] = None,
        entity: Optional[str] = None,
        log_batch_metrics: bool = SETTINGS.log_batch_metrics,
        log_epoch_metrics: bool = SETTINGS.log_epoch_metrics,
        group: Optional[str] = None
    ) -> None:
        super().__init__(log_batch_metrics=log_batch_metrics, log_epoch_metrics=log_epoch_metrics)
        self.project = project
        self.name = name
        self.entity = entity
        self.run = wandb.init(
            project=self.project, name=self.name, entity=self.entity, allow_val_change=True, group=group
        )
```

**Comment by Scitator** [comment]
@AyushExel could we add **kwargs passing to the wandb.init?

**Comment by AyushExel** [comment]
@Scitator yes 👍 , should I make a PR for that?

**Comment by Scitator** [comment]
yeah, that would be nice 👍 
Thanks!
