### ISSUE TITLE
Zero seed error

### ISSUE THREAD

**Issue by ivan-chai** [catalyst-team/catalyst#1320]
## 🐛 Bug Report
Catalyst seeds are started from 1, while torch, random and numpy seeds are started from zero. Assigning zero seed causes error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/catalyst/runners/runner.py", line 515, in train
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/runner.py", line 854, in run
    self._run_event("on_exception")
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/runner.py", line 788, in _run_event
    getattr(self, event)(self)
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/runner.py", line 780, in on_exception
    raise self.exception
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/runner.py", line 850, in run
    self._run_experiment()
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/runner.py", line 840, in _run_experiment
    self.engine.spawn(self._run_stage)
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/engine.py", line 138, in spawn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/runner.py", line 829, in _run_stage
    self._run_event("on_stage_start")
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/runner.py", line 784, in _run_event
    getattr(self, event)(self)
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/runner.py", line 684, in on_stage_start
    self.engine.ddp_sync_run(self._setup_loaders)
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/engine.py", line 159, in ddp_sync_run
    function()
  File "/usr/local/lib/python3.6/dist-packages/catalyst/core/runner.py", line 604, in _setup_loaders
    set_global_seed(self.seed + self.engine.rank + self.global_epoch_step)
  File "/usr/local/lib/python3.6/dist-packages/catalyst/utils/misc.py", line 59, in set_global_seed
    np.random.seed(seed)
  File "mtrand.pyx", line 244, in numpy.random.mtrand.RandomState.seed
  File "_mt19937.pyx", line 166, in numpy.random._mt19937.MT19937._legacy_seeding
  File "_mt19937.pyx", line 180, in numpy.random._mt19937.MT19937._legacy_seeding
ValueError: Seed must be between 0 and 2**32 - 1
```

The source of the problem is rank usage during seed initialization. The rank can be '-1' when ddp is off:
```
set_global_seed(self.seed + self.engine.rank + self.global_epoch_step)
```

### Environment
```
Collecting environment information...
Catalyst version: 21.09
PyTorch version: 1.9.1+cu102
Is debug build: No
CUDA used to build PyTorch: 10.2
TensorFlow version: N/A
TensorBoard version: 2.6.0

OS: linux
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB

Nvidia driver version: 455.45.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] catalyst==21.9
[pip3] numpy==1.19.5
[pip3] tensorboard==2.6.0
[pip3] tensorboard-data-server==0.6.1
[pip3] tensorboard-plugin-wit==1.8.0
[pip3] tensorboardX==2.2
[pip3] torch==1.9.1
[pip3] torchvision==0.10.1
[conda] Could not collect
```

**Comment by Scitator** [comment]
🤔  could you please PR a simple hotfix like
```python
set_global_seed(self.seed + max(0, self.engine.rank) + self.global_epoch_step)
```
?

**Comment by Scitator** [comment]
should be fixed in `master` branch 🎉
