### ISSUE TITLE
Segmentation quickstartnotebook: TypeError: tensor is not a torch image.

### ISSUE THREAD

**Issue by Diyago** [catalyst-team/catalyst#139]
I have several png images with corresponding masks:
Getting data:
``` python
data_dir = './data_objects'

def load_data(root_dir):
    data = []

    for stage in ['train']:
        for content in ['images', 'segmentation']:
            
            # construct path to each image
            directory = os.path.join(root_dir,  content)
            fps = [os.path.join(directory, filename) for filename in os.listdir(directory)]

            # read images

            images = [imread(filepath) for filepath in fps]
 
            # if images have different sizes you have to resize them before:
            resized_images = [resize(image, (64, 64)) for image in images]
            
            # stack to one np.array 
            np_images = np.stack(resized_images, axis=0)
            
            data.append(np_images)
            
    return data
x_train, y_train  = load_data(data_dir)
y_train = y_train.reshape(19, 64, 64, 1)
```
Making data looks like in the example notebook:
``` python
x_train, X_test, y_train, y_test = train_test_split(
         x_train, y_train, test_size=0.33, random_state=42)

train_data = list(zip(x_train, y_train))
valid_data = list(zip(X_test, y_test))
```
> train_data[0][0].shape, train_data[0][1].shape, len(train_data)
(64, 64, 3), (64, 64, 1), 12

Calling `train` returns error:

```
0/10 * Epoch (train):   0% 0/3 [00:00<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-43-69a57e657d9d> in <module>()
     26     logdir=logdir,
     27     num_epochs=num_epochs,
---> 28     verbose=True
     29 )

~/anaconda3/lib/python3.6/site-packages/catalyst/dl/experiments/runner.py in train(self, model, criterion, optimizer, loaders, logdir, callbacks, scheduler, num_epochs, valid_loader, main_metric, minimize_metric, verbose, state_kwargs, check)
    269             state_kwargs=state_kwargs
    270         )
--> 271         self.run_experiment(experiment, check=check)
    272 
    273     def infer(

~/anaconda3/lib/python3.6/site-packages/catalyst/dl/experiments/runner.py in run_experiment(self, experiment, check)
    192         self.experiment = experiment
    193         for stage in self.experiment.stages:
--> 194             self._run_stage(stage)
    195         return self
    196 

~/anaconda3/lib/python3.6/site-packages/catalyst/dl/experiments/runner.py in _run_stage(self, stage)
    173 
    174             self._run_event("epoch_start")
--> 175             self._run_epoch(loaders)
    176             self._run_event("epoch_end")
    177 

~/anaconda3/lib/python3.6/site-packages/catalyst/dl/experiments/runner.py in _run_epoch(self, loaders)
    158             self._run_event("loader_start")
    159             with torch.set_grad_enabled(self.state.need_backward):
--> 160                 self._run_loader(loaders[loader_name])
    161             self._run_event("loader_end")
    162 

~/anaconda3/lib/python3.6/site-packages/catalyst/dl/experiments/runner.py in _run_loader(self, loader)
    119         self.state.timer.start("base/data_time")
    120 
--> 121         for i, batch in enumerate(loader):
    122             batch = self._batch2device(batch, self.device)
    123             self.state.timer.stop("base/data_time")

~/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    635                 self.reorder_dict[idx] = batch
    636                 continue
--> 637             return self._process_next_batch(batch)
    638 
    639     next = __next__  # Python 2 compatibility

~/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    656         self._put_indices()
    657         if isinstance(batch, ExceptionWrapper):
--> 658             raise batch.exc_type(batch.exc_msg)
    659         return batch
    660 

TypeError: Traceback (most recent call last):
  File "/home/dex/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/dex/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/dex/anaconda3/lib/python3.6/site-packages/catalyst/data/dataset.py", line 74, in __getitem__
    dict_ = self.dict_transform(dict_)
  File "/home/dex/anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/transforms.py", line 42, in __call__
    img = t(img)
  File "/home/dex/anaconda3/lib/python3.6/site-packages/catalyst/data/augmentor.py", line 25, in __call__
    ] = self.augment_fn(dict_[self.dict_key], **self.default_kwargs)
  File "/home/dex/anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/transforms.py", line 118, in __call__
    return F.normalize(tensor, self.mean, self.std)
  File "/home/dex/anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/functional.py", line 158, in normalize
    raise TypeError('tensor is not a torch image.')
TypeError: tensor is not a torch image.
```

Then I tried adding more transforms, but failed to fix that problem, for example something like this:

``` python
data_transform = transforms.Compose([
    Augmentor(
        dict_key="features",
        augment_fn=lambda x: \
            torch.from_numpy(x.copy().astype(np.float32) / 255.).unsqueeze_(0)),
    Augmentor(
        dict_key="features",
        augment_fn=transforms.ToPILImage()),  #transforms.ToTensor()),
    Augmentor(
        dict_key="features",
        augment_fn=transforms.Normalize(
            (0.5, 0.5, 0.5),
            (0.5, 0.5, 0.5))),
    Augmentor(
        dict_key="targets",
        augment_fn=lambda x: \
            torch.from_numpy(x.copy().astype(np.float32) / 255.).unsqueeze_(0)),
    Augmentor(
        dict_key="targets",
        augment_fn= transforms.ToPILImage())#transforms.ToTensor())
])
```

What is wrong here?

**Comment by Diyago** [comment]
Dataset is pretty small, just for checking pipeline https://drive.google.com/open?id=1xGUc2KXILpHL4ZTTpSYp05_MOhmWKT3r

**Comment by Scitator** [comment]
Check your augmentations (at least, you need to pass `Tensors` to the network, rather than `PILImages`).
Have you to manage to run [segmentation notebook](https://github.com/catalyst-team/catalyst/blob/master/examples/segmentation-example.ipynb) without any modifications?

PS. as a sanity check, you can take augmentations from [segmentation notebook example](https://github.com/catalyst-team/catalyst/blob/master/examples/segmentation-example.ipynb).
