### ISSUE TITLE
AttributeError: 'SummaryWriter' object has no attribute 'flush'

### ISSUE THREAD

**Issue by ternaus** [catalyst-team/catalyst#305]
```
Traceback (most recent call last):
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/catalyst/dl/core/runner.py", line 193, in run_experiment
    self._run_stage(stage)
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/catalyst/dl/core/runner.py", line 175, in _run_stage
    self._run_epoch(loaders)
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/catalyst/dl/core/runner.py", line 163, in _run_epoch
    self._run_event("loader_end")
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/catalyst/dl/core/runner.py", line 96, in _run_event
    getattr(self.state, f"on_{event}_post")()
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/catalyst/dl/core/state.py", line 159, in on_loader_end_post
    logger.on_loader_end(self)
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/catalyst/dl/callbacks/logging.py", line 175, in on_loader_end
    logger.flush()
AttributeError: 'SummaryWriter' object has no attribute 'flush'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vladimir/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/vladimir/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/6e9adcc8-9cfe-4dbb-aaff-c2ae9c64a9bc/workspace/kaggle_severstal/src/train.py", line 161, in <module>
    main()
  File "/mnt/6e9adcc8-9cfe-4dbb-aaff-c2ae9c64a9bc/workspace/kaggle_severstal/src/train.py", line 156, in main
    minimize_metric=False
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/catalyst/dl/runner/supervised.py", line 129, in train
    self.run_experiment(experiment, check=check)
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/catalyst/dl/core/runner.py", line 196, in run_experiment
    self._run_event("exception")
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/catalyst/dl/core/runner.py", line 93, in _run_event
    getattr(callback, f"on_{event}")(self.state)
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/catalyst/dl/callbacks/checkpoint.py", line 71, in on_exception
    is_last=False
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/catalyst/utils/checkpoint.py", line 71, in save_checkpoint
    torch.save(checkpoint, filename)
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 224, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 149, in _with_file_like
    return body(f)
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 224, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/vladimir/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 296, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'MetricManager.begin_epoch.<locals>.<lambda>'

```

**Comment by Scitator** [comment]
should be fixed by requirements update in https://github.com/catalyst-team/catalyst/pull/304
