### ISSUE TITLE
Atari example fails with an error

### ISSUE THREAD

**Issue by Felix-neko** [catalyst-team/catalyst#314]
Hi! I'm trying to run atari example just like in the manual and get the following error:

`CUDA_VISIBLE_DEVICES="" catalyst-rl run-samplers --config=./config_dqn.yml
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/catalyst/rl/scripts/run_samplers.py", line 94, in run_sampler
    sampler_id=id,
  File "/mnt/host_misc/catalyst/examples/atari/src/env.py", line 23, in __init__
    self.env = make_atari_env(**params)
TypeError: make_atari_env() got an unexpected keyword argument 'sampler_id'
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/catalyst/rl/scripts/run_samplers.py", line 94, in run_sampler
    sampler_id=id,
  File "/mnt/host_misc/catalyst/examples/atari/src/env.py", line 23, in __init__
    self.env = make_atari_env(**params)
TypeError: make_atari_env() got an unexpected keyword argument 'sampler_id'
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/catalyst/rl/scripts/run_samplers.py", line 94, in run_sampler
    sampler_id=id,
  File "/mnt/host_misc/catalyst/examples/atari/src/env.py", line 23, in __init__
    self.env = make_atari_env(**params)
TypeError: make_atari_env() got an unexpected keyword argument 'sampler_id'
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/catalyst/rl/scripts/run_samplers.py", line 94, in run_sampler
    sampler_id=id,
  File "/mnt/host_misc/catalyst/examples/atari/src/env.py", line 23, in __init__
    self.env = make_atari_env(**params)
TypeError: make_atari_env() got an unexpected keyword argument 'sampler_id'
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/catalyst/rl/scripts/run_samplers.py", line 94, in run_sampler
    sampler_id=id,
  File "/mnt/host_misc/catalyst/examples/atari/src/env.py", line 23, in __init__
    self.env = make_atari_env(**params)
TypeError: make_atari_env() got an unexpected keyword argument 'sampler_id'
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/catalyst/rl/scripts/run_samplers.py", line 94, in run_sampler
    sampler_id=id,
  File "/mnt/host_misc/catalyst/examples/atari/src/env.py", line 23, in __init__
    self.env = make_atari_env(**params)
TypeError: make_atari_env() got an unexpected keyword argument 'sampler_id'
Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/catalyst/rl/scripts/run_samplers.py", line 94, in run_sampler
    sampler_id=id,
  File "/mnt/host_misc/catalyst/examples/atari/src/env.py", line 23, in __init__
    self.env = make_atari_env(**params)
TypeError: make_atari_env() got an unexpected keyword argument 'sampler_id'
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/catalyst/rl/scripts/run_samplers.py", line 94, in run_sampler
    sampler_id=id,
  File "/mnt/host_misc/catalyst/examples/atari/src/env.py", line 23, in __init__
    self.env = make_atari_env(**params)
TypeError: make_atari_env() got an unexpected keyword argument 'sampler_id'
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/catalyst/rl/scripts/run_samplers.py", line 94, in run_sampler
    sampler_id=id,
  File "/mnt/host_misc/catalyst/examples/atari/src/env.py", line 23, in __init__
    self.env = make_atari_env(**params)
TypeError: make_atari_env() got an unexpected keyword argument 'sampler_id'
`

Can you tell me how to fix it?

**Comment by Felix-neko** [comment]
Please take a PR.

**Comment by Scitator** [comment]
Hi,

You are right, there is an issue with `sampler_id`. The correct way to handle it can be found [here](https://github.com/catalyst-team/catalyst/blob/master/catalyst/rl/environment/gym.py#L26).

**Comment by Scitator** [comment]
fixed
