### ISSUE TITLE
classification-tutorial notebook fails with an error on multi-GPU machine

### ISSUE THREAD

**Issue by Felix-neko** [catalyst-team/catalyst#334]
Hi! I'm trying to run your `classifcation-tutorial` notebook on a multi-gpu node.

Alas, it fails with the following error message:

```
0/10 * Epoch (train):   0% 0/106 [00:00<?, ?it/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-123-bb8ae99f70ba> in <module>
     21     ],
     22     num_epochs=NUM_EPOCHS,
---> 23     verbose=True
     24 )

/mnt/host_dump/catalyst/catalyst/dl/runner/supervised.py in train(self, model, criterion, optimizer, loaders, logdir, callbacks, scheduler, num_epochs, valid_loader, main_metric, minimize_metric, verbose, state_kwargs, checkpoint_data, fp16, check)
    127             distributed_params=fp16
    128         )
--> 129         self.run_experiment(experiment, check=check)
    130 
    131     def infer(

/mnt/host_dump/catalyst/catalyst/dl/core/runner.py in run_experiment(self, experiment, check)
    194         except (Exception, KeyboardInterrupt) as ex:
    195             self.state.exception = ex
--> 196             self._run_event("exception")
    197 
    198         return self

/mnt/host_dump/catalyst/catalyst/dl/core/runner.py in _run_event(self, event)
     94 
     95         if self.state is not None and hasattr(self.state, f"on_{event}_post"):
---> 96             getattr(self.state, f"on_{event}_post")()
     97 
     98     @abstractmethod

/mnt/host_dump/catalyst/catalyst/dl/core/state.py in on_exception_post(self)
    170     def on_exception_post(self):
    171         for logger in self.loggers:
--> 172             logger.on_exception(self)
    173 
    174 

/mnt/host_dump/catalyst/catalyst/dl/callbacks/logging.py in on_exception(self, state)
    187 
    188         if state.need_reraise_exception:
--> 189             raise exception
    190 
    191 

/mnt/host_dump/catalyst/catalyst/dl/core/runner.py in run_experiment(self, experiment, check)
    191         try:
    192             for stage in self.experiment.stages:
--> 193                 self._run_stage(stage)
    194         except (Exception, KeyboardInterrupt) as ex:
    195             self.state.exception = ex

/mnt/host_dump/catalyst/catalyst/dl/core/runner.py in _run_stage(self, stage)
    173 
    174             self._run_event("epoch_start")
--> 175             self._run_epoch(loaders)
    176             self._run_event("epoch_end")
    177 

/mnt/host_dump/catalyst/catalyst/dl/core/runner.py in _run_epoch(self, loaders)
    160             self._run_event("loader_start")
    161             with torch.set_grad_enabled(self.state.need_backward):
--> 162                 self._run_loader(loader)
    163             self._run_event("loader_end")
    164 

/mnt/host_dump/catalyst/catalyst/dl/core/runner.py in _run_loader(self, loader)
    129 
    130         for i, batch in enumerate(loader):
--> 131             self._run_batch(batch)
    132 
    133             self.state.timer.reset()

/mnt/host_dump/catalyst/catalyst/dl/core/runner.py in _run_batch(self, batch)
    108         self._run_event("batch_start")
    109         self.state.timer.start("_timers/model_time")
--> 110         self.state.output = self.predict_batch(batch)
    111         self.state.timer.stop("_timers/model_time")
    112         self.state.timer.stop("_timers/batch_time")

/mnt/host_dump/catalyst/catalyst/dl/runner/supervised.py in predict_batch(self, batch)
     84 
     85     def predict_batch(self, batch: Mapping[str, Any]):
---> 86         output = self._process_input(batch)
     87         output = self._process_output(output)
     88         return output

/mnt/host_dump/catalyst/catalyst/dl/runner/supervised.py in _process_input_str(self, batch)
     58 
     59     def _process_input_str(self, batch: Mapping[str, Any]):
---> 60         output = self.model(batch[self.input_key])
     61         return output
     62 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/data_parallel.py in forward(self, *inputs, **kwargs)
    150             return self.module(*inputs[0], **kwargs[0])
    151         replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
--> 152         outputs = self.parallel_apply(replicas, inputs, kwargs)
    153         return self.gather(outputs, self.output_device)
    154 

/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/data_parallel.py in parallel_apply(self, replicas, inputs, kwargs)
    160 
    161     def parallel_apply(self, replicas, inputs, kwargs):
--> 162         return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
    163 
    164     def gather(self, outputs, output_device):

/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/parallel_apply.py in parallel_apply(modules, inputs, kwargs_tup, devices)
     83         output = results[i]
     84         if isinstance(output, ExceptionWrapper):
---> 85             output.reraise()
     86         outputs.append(output)
     87     return outputs

/usr/local/lib/python3.7/dist-packages/torch/_utils.py in reraise(self)
    367             # (https://bugs.python.org/issue2651), so we work around it.
    368             msg = KeyErrorMessage(msg)
--> 369         raise self.exc_type(msg)

RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pretrainedmodels/models/torchvision_models.py", line 340, in forward
    x = self.features(input)
  File "/usr/local/lib/python3.7/dist-packages/pretrainedmodels/models/torchvision_models.py", line 322, in features
    x = self.conv1(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)

```

How can I fix it?

P.S. I've set `os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"`, it had no effect. I've also set I've set `os.environ["CUDA_VISIBLE_DEVICES"] = "", it gave the same message. `os.environ["CUDA_VISIBLE_DEVICES"] = "0" also gave the same message.

**Comment by Scitator** [comment]
Could you please confirm, that everything works like a charm during colab run?

**Comment by Scitator** [comment]
closed due to inactivity
