### ISSUE TITLE
Error after resuming model training with multiple criterions

### ISSUE THREAD

**Issue by fanranGit** [catalyst-team/catalyst#363]
When I'm trying to resume model training with last checkpoint I get an error: 
```
=> loading checkpoint /mnt/hdd1/users/vzaborovskiy/logdir/model/checkpoints/last.pth
Traceback (most recent call last):
  File "/home/vzaborovsky/.conda/envs/enn/bin/catalyst-dl", line 11, in <module>
    load_entry_point('catalyst', 'console_scripts', 'catalyst-dl')()
  File "/home/vzaborovsky/catalyst/catalyst/dl/__main__.py", line 43, in main
    COMMANDS[args.command].main(args, uargs)
  File "/home/vzaborovsky/catalyst/catalyst/dl/scripts/run.py", line 85, in main
    runner.run_experiment(experiment, check=args.check)
  File "/home/vzaborovsky/catalyst/catalyst/dl/core/runner.py", line 196, in run_experiment
    self._run_event("exception")
  File "/home/vzaborovsky/catalyst/catalyst/dl/core/runner.py", line 96, in _run_event
    getattr(self.state, f"on_{event}_post")()
  File "/home/vzaborovsky/catalyst/catalyst/dl/core/state.py", line 177, in on_exception_post
    logger.on_exception(self)
  File "/home/vzaborovsky/catalyst/catalyst/dl/callbacks/logging.py", line 194, in on_exception
    raise exception
  File "/home/vzaborovsky/catalyst/catalyst/dl/core/runner.py", line 193, in run_experiment
    self._run_stage(stage)
  File "/home/vzaborovsky/catalyst/catalyst/dl/core/runner.py", line 170, in _run_stage
    self._run_event("stage_start")
  File "/home/vzaborovsky/catalyst/catalyst/dl/core/runner.py", line 93, in _run_event
    getattr(callback, f"on_{event}")(self.state)
  File "/home/vzaborovsky/catalyst/catalyst/dl/callbacks/checkpoint.py", line 211, in on_stage_start
    self.load_checkpoint(filename=self.resume, state=state)
  File "/home/vzaborovsky/catalyst/catalyst/dl/callbacks/checkpoint.py", line 121, in load_checkpoint
    scheduler=state.scheduler
  File "/home/vzaborovsky/catalyst/catalyst/utils/checkpoint.py", line 79, in unpack_checkpoint
    value.load_state_dict(checkpoint[name2load_])
KeyError: 'criterion_hm_state_dict'
```
Seems like catalyst doesn't save all losses states. `'criterion_hm_state_dict'` relates to the one of losses, hm is a key in criterion params. Config looks like that:

```
  criterion_params:
    _key_value: True

    hm:
      criterion: MyLoss
    l1_wh:
      criterion: RegL1Loss
      key: wh
    l1_reg:
      criterion: RegL1Loss
      key: reg
```

**Comment by Scitator** [comment]
Could you please add some minimal example to reproduce the issue?

**Comment by fanranGit** [comment]
Fixed with checkpoint `_full` version.  Everything works if I resume training with last_full.pth
