### ISSUE TITLE
Model tracing failed

### ISSUE THREAD

**Issue by fanranGit** [catalyst-team/catalyst#392]
When I'm trying to trace model with command: `CUDA_VISIBLE_DEVICES=2 catalyst-dl trace /path_to/my_model_logdir -c best -m predict`
get an error:
```
Load config
Import experiment and runner from logdir
Load model state from checkpoints/best_full.pth
Tracing
Traceback (most recent call last):
  File "/home/vzaborovsky/.conda/envs/centernet_catalyst/bin/catalyst-dl", line 10, in <module>
    sys.exit(main())
  File "/home/vzaborovsky/.conda/envs/centernet_catalyst/lib/python3.7/site-packages/catalyst/dl/__main__.py", line 43, in main
    COMMANDS[args.command].main(args, uargs)
  File "/home/vzaborovsky/.conda/envs/centernet_catalyst/lib/python3.7/site-packages/catalyst/dl/scripts/trace.py", line 117, in main
    requires_grad=requires_grad,
  File "/home/vzaborovsky/.conda/envs/centernet_catalyst/lib/python3.7/site-packages/catalyst/dl/scripts/trace.py", line 46, in trace_model_from_checkpoint
    requires_grad=requires_grad,
  File "/home/vzaborovsky/.conda/envs/centernet_catalyst/lib/python3.7/site-packages/catalyst/dl/utils/trace.py", line 96, in trace_model
    runner: Runner = runner_type(tracer.cpu(), torch.device("cpu"))
TypeError: __init__() takes 1 positional argument but 3 were given
```

Version: 19.9.5

**Comment by fanranGit** [comment]
Config api.
Runner:
```
from catalyst.dl import SupervisedRunner

class Runner(SupervisedRunner):
    def __init__(self):
        super().__init__(input_key="input", output_key=None)
```

**Comment by fanranGit** [comment]
For now problem solved with adding missing arguments to runner:  
```
from catalyst.dl import SupervisedRunner

class Runner(SupervisedRunner):
    def __init__(self, model=None, device=None):
        super().__init__(input_key="input", output_key=None, model=model, device=device)
```

**Comment by Scitator** [comment]
Please, check the [Runner](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/core/runner.py#L17) init signature. You should have `model` and `device` as a parameters
