### ISSUE TITLE
tensorboard - 'tensorflow._api.v1.io' has no attribute 'gfile'

### ISSUE THREAD

**Issue by Yorko** [catalyst-team/catalyst#465]
**Describe the bug**

When running the basic `cifar_simple` example, tensorboard throws AttributeError: module 'tensorflow._api.v1.io' has no attribute 'gfile'

**To Reproduce**
1. Checkout the master branch  
2. Install catalyst-19.10.2 from source: `pip install -e .`
3. `cd examples`
4. `catalyst-dl run -C cifar_simple/config.yml` 

Python 3.6. 

```
Package versions:
tensorboard                        2.0.0      
tensorboardX                       1.9        
tensorflow-estimator               2.0.0      
tensorflow-gpu                     1.12.0     
tensorflow-hub                     0.2.0 
```

**Expected behavior**

Expected to run the example. 

**Screenshots**

```
Traceback (most recent call last):
  File "/home/kashn500/anaconda3/bin/catalyst-dl", line 11, in <module>
    load_entry_point('catalyst', 'console_scripts', 'catalyst-dl')()
  File "/home/kashn500/ML/catalyst/catalyst/dl/__main__.py", line 44, in main
    COMMANDS[args.command].main(args, uargs)
  File "/home/kashn500/ML/catalyst/catalyst/dl/scripts/run.py", line 82, in main
    dump_environment(config, experiment.logdir, args.configs)
  File "/home/kashn500/ML/catalyst/catalyst/utils/config.py", line 205, in dump_environment
    with SummaryWriter(config_dir) as writer:
  File "/home/kashn500/anaconda3/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 221, in __init__
    self._get_file_writer()
  File "/home/kashn500/anaconda3/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 252, in _get_file_writer
    self.flush_secs, self.filename_suffix)
  File "/home/kashn500/anaconda3/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 62, in __init__
    log_dir, max_queue, flush_secs, filename_suffix)
  File "/home/kashn500/anaconda3/lib/python3.6/site-packages/tensorboard/summary/writer/event_file_writer.py", line 73, in __init__
    if not tf.io.gfile.exists(logdir):
AttributeError: module 'tensorflow._api.v1.io' has no attribute 'gfile'
```

**Additional context**

**Comment by Yorko** [comment]
Actually, the same error when running `sh bin/check_dl.sh`

**Comment by Yorko** [comment]
Well.... actually, I wasn't able to reproduce the error - so I'm closing the issue.

In a freshly created conda environment workes fine, though the `tensorboard` version is the same, strange. Whatever
