### ISSUE TITLE
Error loading from checkpoint

### ISSUE THREAD

**Issue by ternaus** [catalyst-team/catalyst#680]
Loading weights from checkpoint:

```
callbacks = [CheckpointCallback(resume=args.checkpoint_path)]

runner = SupervisedRunner()
    runner.train(
        model=model,
        criterion=config.loss,
        optimizer=config.optimizer,
        callbacks=callbacks,
        logdir=config.logdir,
        loaders=data_loaders,
        num_epochs=config.train_parameters.num_epochs,
        # scheduler=config.scheduler,
        verbose=True,
        minimize_metric=True,
        fp16=config.train_parameters.fp16,
        valid_loader="train",
    )
```

Get an error

```
=> loading checkpoint /home/vladimir/workspace/evo970/data/kaggle_deepfake/checkpoints/resnext50_32x4d/logs/checkpoints/last_full.pth
loaded checkpoint /home/vladimir/workspace/evo970/data/kaggle_deepfake/checkpoints/resnext50_32x4d/logs/checkpoints/last_full.pth (epoch 119, stage_epoch 119, stage train)
Traceback (most recent call last):
  File "/home/vladimir/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/vladimir/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/evo850/workspace/kaggle_deepfake/kaggle_deepfake/train.py", line 126, in <module>
    main()
  File "/mnt/evo850/workspace/kaggle_deepfake/kaggle_deepfake/train.py", line 121, in main
    valid_loader="train",
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/catalyst/dl/runner/supervised.py", line 206, in train
    self.run_experiment(experiment, check=check)
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/catalyst/core/runner.py", line 389, in run_experiment
    self._run_event("exception", moment=None)
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/catalyst/core/runner.py", line 234, in _run_event
    getattr(logger, fn_name)(self.state)
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/catalyst/dl/callbacks/misc.py", line 152, in on_exception
    raise exception
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/catalyst/core/runner.py", line 381, in run_experiment
    self._run_stage(stage)
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/catalyst/core/runner.py", line 342, in _run_stage
    self._run_event("stage", moment="start")
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/catalyst/core/runner.py", line 228, in _run_event
    getattr(callback, fn_name)(self.state)
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/catalyst/core/callbacks/checkpoint.py", line 222, in on_stage_start
    state.resume = None
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/catalyst/utils/tools/frozen_class.py", line 12, in __setattr__
    raise TypeError("%r is a frozen class" % self)

```

**Comment by Scitator** [comment]
Hi, thanks for issue track.
There was a bug into previous version, you can use `20.02.4` instead.
