### ISSUE TITLE
SupervisedWandbRunner error when predict_loader

### ISSUE THREAD

**Issue by jesusmolrdv** [catalyst-team/catalyst#686]
**Describe the bug**
When using `SupervisedWandbRunner` calling `predict_loader` throws an exception:

```
Traceback (most recent call last):
  File "prueba.py", line 187, in <module>
    verbose=True,
  File "/opt/conda/lib/python3.6/site-packages/catalyst/dl/runner/supervised.py", line 292, in predict_loader
    check=check
  File "/opt/conda/lib/python3.6/site-packages/catalyst/dl/runner/supervised.py", line 250, in infer
    self.run_experiment(experiment, check=check)
  File "/opt/conda/lib/python3.6/site-packages/catalyst/contrib/dl/runner/wandb.py", line 141, in run_experiment
    self._pre_experiment_hook(experiment=experiment)
  File "/opt/conda/lib/python3.6/site-packages/catalyst/contrib/dl/runner/wandb.py", line 60, in _pre_experiment_hook
    monitoring_params["dir"] = str(Path(experiment.logdir).absolute())
  File "/opt/conda/lib/python3.6/pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "/opt/conda/lib/python3.6/pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/opt/conda/lib/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
``` 

**To Reproduce**
Calling
```
predictions = runner.predict_loader(
        model=model,
        loader=loaders["valid"],
        resume="{}/checkpoints/best.pth".format(logdir),
        verbose=True,
    )
```
After training the model leads into the exception.

**Additional context**
After some research, I have found that the problem is that in [this line](https://github.com/catalyst-team/catalyst/blob/37bddea809cb0aab982063940d7ba247ad3aad5c/catalyst/contrib/dl/runner/wandb.py#L60) the code expects the experiment logdir to be defined, but when calling `predict_loader` that is not possible.

It is the same error described in #603 but it is closed while the problem is still present.

**Comment by jesusmolrdv** [comment]
Just seen #603 so I am closing the issue. Sorry for the inconvenience.
