### ISSUE TITLE
Distributed mode fail

### ISSUE THREAD

**Issue by balakhonoff** [catalyst-team/catalyst#767]
**Describe the bug**
Here is the thing. I used the new feature DistributedDataParallel in notebook API with Distilbert from huggingface and it was cool. But when I tried to change the model to BERT, I found out that the catalyst works in a notebook (with distributed=False) and fails in script (with distributed=True)

**To Reproduce**
1. run a notebook (https://yadi.sk/d/Agr5JkPH-SppuA ) -> it works ok 
2. convert it to script: `jupyter nbconvert --to script example_to_reproduce_an_error.ipynb`
3. run the script: `python example_to_reproduce_an_error.py` -> it fails with the trace:
`Traceback (most recent call last):
  File "v71_pytorch_distilbert_is_is_v4_with_main_auc_first_stage_notmulti.py", line 530, in <module>
    minimize_metric=False
  File "/home/kb/.local/lib/python3.7/site-packages/catalyst/dl/runner/core.py", line 133, in train
    utils.distributed_cmd_run(self.run_experiment, distributed)
  File "/home/kb/.local/lib/python3.7/site-packages/catalyst/utils/scripts.py", line 133, in distributed_cmd_run
    worker_fn(*args, **kwargs)
  File "/home/kb/.local/lib/python3.7/site-packages/catalyst/core/runner.py", line 510, in run_experiment
    self._run_event("on_exception")
  File "/home/kb/.local/lib/python3.7/site-packages/catalyst/core/runner.py", line 329, in _run_event
    getattr(callback, event)(self.state)
  File "/home/kb/.local/lib/python3.7/site-packages/catalyst/core/callbacks/exception.py", line 20, in on_exception
    raise exception
  File "/home/kb/.local/lib/python3.7/site-packages/catalyst/core/runner.py", line 497, in run_experiment
    self._run_stage(stage)
  File "/home/kb/.local/lib/python3.7/site-packages/catalyst/core/runner.py", line 474, in _run_stage
    self._run_epoch(stage=stage, epoch=state.epoch)
  File "/home/kb/.local/lib/python3.7/site-packages/catalyst/core/runner.py", line 451, in _run_epoch
    self._run_loader(loader)
  File "/home/kb/.local/lib/python3.7/site-packages/catalyst/core/runner.py", line 398, in _run_loader
    self._run_batch(batch)
  File "/home/kb/.local/lib/python3.7/site-packages/catalyst/core/runner.py", line 375, in _run_batch
    self._handle_batch(batch=batch)
  File "/home/kb/.local/lib/python3.7/site-packages/catalyst/dl/runner/supervised.py", line 135, in _handle_batch
    self.state.batch_out = self.forward(batch)
  File "/home/kb/.local/lib/python3.7/site-packages/catalyst/dl/runner/supervised.py", line 122, in forward
    output = self._process_input(batch, **kwargs)
  File "/home/kb/.local/lib/python3.7/site-packages/catalyst/dl/runner/supervised.py", line 88, in _process_input_str
    output = self.model(batch[self.input_key], **kwargs)
  File "/home/kb/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kb/.local/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 464, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:514)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7efc40902193 in /home/kb/.local/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10d::Reducer::prepare_for_backward(std::vector<at::Tensor, std::allocator<at::Tensor> > const&) + 0x731 (0x7efc8c0c26f1 in /home/kb/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0xa168ea (0x7efc8c0ae8ea in /home/kb/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x295a74 (0x7efc8b92da74 in /home/kb/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: _PyMethodDef_RawFastCallKeywords + 0x264 (0x555be3a68114 in /home/kb/anaconda3/bin/python3)
frame #5: _PyCFunction_FastCallKeywords + 0x21 (0x555be3a68231 in /home/kb/anaconda3/bin/python3)
frame #6: _PyEval_EvalFrameDefault + 0x52cf (0x555be3acce8f in /home/kb/anaconda3/bin/python3)
frame #7: _PyEval_EvalCodeWithName + 0x2f9 (0x555be3a216f9 in /home/kb/anaconda3/bin/python3)
frame #8: _PyFunction_FastCallDict + 0x1d5 (0x555be3a22805 in /home/kb/anaconda3/bin/python3)
frame #9: _PyObject_Call_Prepend + 0x63 (0x555be3a3d943 in /home/kb/anaconda3/bin/python3)
frame #10: PyObject_Call + 0x6e (0x555be3a30b9e in /home/kb/anaconda3/bin/python3)
frame #11: _PyEval_EvalFrameDefault + 0x1e35 (0x555be3ac99f5 in /home/kb/anaconda3/bin/python3)
frame #12: _PyEval_EvalCodeWithName + 0x2f9 (0x555be3a216f9 in /home/kb/anaconda3/bin/python3)
frame #13: _PyFunction_FastCallDict + 0x1d5 (0x555be3a22805 in /home/kb/anaconda3/bin/python3)
frame #14: _PyObject_Call_Prepend + 0x63 (0x555be3a3d943 in /home/kb/anaconda3/bin/python3)
frame #15: <unknown function> + 0x17512a (0x555be3a7c12a in /home/kb/anaconda3/bin/python3)
frame #16: PyObject_Call + 0x6e (0x555be3a30b9e in /home/kb/anaconda3/bin/python3)
frame #17: _PyEval_EvalFrameDefault + 0x1e35 (0x555be3ac99f5 in /home/kb/anaconda3/bin/python3)
frame #18: _PyEval_EvalCodeWithName + 0x2f9 (0x555be3a216f9 in /home/kb/anaconda3/bin/python3)
frame #19: _PyFunction_FastCallDict + 0x1d5 (0x555be3a22805 in /home/kb/anaconda3/bin/python3)
frame #20: _PyObject_Call_Prepend + 0x63 (0x555be3a3d943 in /home/kb/anaconda3/bin/python3)
frame #21: PyObject_Call + 0x6e (0x555be3a30b9e in /home/kb/anaconda3/bin/python3)
frame #22: _PyEval_EvalFrameDefault + 0x1e35 (0x555be3ac99f5 in /home/kb/anaconda3/bin/python3)
frame #23: _PyEval_EvalCodeWithName + 0x2f9 (0x555be3a216f9 in /home/kb/anaconda3/bin/python3)
frame #24: _PyFunction_FastCallKeywords + 0x387 (0x555be3a67917 in /home/kb/anaconda3/bin/python3)
frame #25: _PyEval_EvalFrameDefault + 0x6a0 (0x555be3ac8260 in /home/kb/anaconda3/bin/python3)
frame #26: _PyEval_EvalCodeWithName + 0x2f9 (0x555be3a216f9 in /home/kb/anaconda3/bin/python3)
frame #27: _PyFunction_FastCallKeywords + 0x387 (0x555be3a67917 in /home/kb/anaconda3/bin/python3)
frame #28: _PyEval_EvalFrameDefault + 0x14e6 (0x555be3ac90a6 in /home/kb/anaconda3/bin/python3)
frame #29: _PyFunction_FastCallKeywords + 0xfb (0x555be3a6768b in /home/kb/anaconda3/bin/python3)
frame #30: _PyEval_EvalFrameDefault + 0x6a0 (0x555be3ac8260 in /home/kb/anaconda3/bin/python3)
frame #31: _PyFunction_FastCallKeywords + 0xfb (0x555be3a6768b in /home/kb/anaconda3/bin/python3)
frame #32: _PyEval_EvalFrameDefault + 0x6a0 (0x555be3ac8260 in /home/kb/anaconda3/bin/python3)
frame #33: _PyEval_EvalCodeWithName + 0x2f9 (0x555be3a216f9 in /home/kb/anaconda3/bin/python3)
frame #34: _PyFunction_FastCallKeywords + 0x387 (0x555be3a67917 in /home/kb/anaconda3/bin/python3)
frame #35: _PyEval_EvalFrameDefault + 0x14e6 (0x555be3ac90a6 in /home/kb/anaconda3/bin/python3)
frame #36: _PyFunction_FastCallKeywords + 0xfb (0x555be3a6768b in /home/kb/anaconda3/bin/python3)
frame #37: _PyEval_EvalFrameDefault + 0x6a0 (0x555be3ac8260 in /home/kb/anaconda3/bin/python3)
frame #38: _PyEval_EvalCodeWithName + 0x2f9 (0x555be3a216f9 in /home/kb/anaconda3/bin/python3)
frame #39: _PyFunction_FastCallDict + 0x1d5 (0x555be3a22805 in /home/kb/anaconda3/bin/python3)
frame #40: _PyObject_Call_Prepend + 0x63 (0x555be3a3d943 in /home/kb/anaconda3/bin/python3)
frame #41: PyObject_Call + 0x6e (0x555be3a30b9e in /home/kb/anaconda3/bin/python3)
frame #42: _PyEval_EvalFrameDefault + 0x1e35 (0x555be3ac99f5 in /home/kb/anaconda3/bin/python3)
frame #43: _PyEval_EvalCodeWithName + 0x2f9 (0x555be3a216f9 in /home/kb/anaconda3/bin/python3)
frame #44: _PyFunction_FastCallKeywords + 0x387 (0x555be3a67917 in /home/kb/anaconda3/bin/python3)
frame #45: _PyEval_EvalFrameDefault + 0x4b09 (0x555be3acc6c9 in /home/kb/anaconda3/bin/python3)
frame #46: _PyEval_EvalCodeWithName + 0xc30 (0x555be3a22030 in /home/kb/anaconda3/bin/python3)
frame #47: _PyFunction_FastCallKeywords + 0x387 (0x555be3a67917 in /home/kb/anaconda3/bin/python3)
frame #48: _PyEval_EvalFrameDefault + 0x14e6 (0x555be3ac90a6 in /home/kb/anaconda3/bin/python3)
frame #49: _PyEval_EvalCodeWithName + 0x2f9 (0x555be3a216f9 in /home/kb/anaconda3/bin/python3)
frame #50: PyEval_EvalCodeEx + 0x44 (0x555be3a225f4 in /home/kb/anaconda3/bin/python3)
frame #51: PyEval_EvalCode + 0x1c (0x555be3a2261c in /home/kb/anaconda3/bin/python3)
frame #52: <unknown function> + 0x21c974 (0x555be3b23974 in /home/kb/anaconda3/bin/python3)
frame #53: PyRun_FileExFlags + 0xa1 (0x555be3b2dcf1 in /home/kb/anaconda3/bin/python3)
frame #54: PyRun_SimpleFileExFlags + 0x1c3 (0x555be3b2dee3 in /home/kb/anaconda3/bin/python3)
frame #55: <unknown function> + 0x227f95 (0x555be3b2ef95 in /home/kb/anaconda3/bin/python3)
frame #56: _Py_UnixMain + 0x3c (0x555be3b2f0bc in /home/kb/anaconda3/bin/python3)
frame #57: __libc_start_main + 0xe7 (0x7efc9a3ceb97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #58: <unknown function> + 0x1d0990 (0x555be3ad7990 in /home/kb/anaconda3/bin/python3)
`

**Expected behavior**
Normal distributed training like with DistilBERT

**Screenshots**
Not sure what to add

**Additional context**
You guys are cool

**Comment by balakhonoff** [comment]
Tried with XLA Roberta - same issue
I use cuda 10.2 (which one is the recommended?)
result of pip freeze:
absl-py==0.9.0
alchemy==20.4
astor==0.8.1
astunparse==1.6.3
attrs==19.3.0
backcall==0.1.0
bleach==3.1.4
boto3==1.12.39
botocore==1.15.39
cachetools==4.1.0
catalyst==20.4.1
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.1
crc32c==2.0
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
deprecation==2.0.7
docutils==0.15.2
entrypoints==0.3
filelock==3.0.12
gast==0.3.3
gitdb==4.0.4
GitPython==3.1.1
google-auth==1.13.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.28.1
h5py==2.10.0
idna==2.8
imageio==2.8.0
importlib-metadata==1.6.0
ipykernel==5.2.0
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.16.0
Jinja2==2.11.2
jmespath==0.9.5
joblib==0.14.1
jsonschema==3.2.0
jupyter-client==6.1.2
jupyter-core==4.6.3
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.2.0
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.2.1
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.0.6
networkx==2.4
nltk==3.5
notebook==6.0.3
numpy==1.18.2
oauthlib==3.1.0
opencv-python==4.2.0.34
opt-einsum==3.2.1
packaging==20.3
pandas==1.0.3
pandocfilters==1.4.2
parso==0.6.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==6.2.2
plotly==4.6.0
prometheus-client==0.7.1
prompt-toolkit==3.0.5
protobuf==3.11.3
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.0
regex==2020.4.4
requests==2.22.0
requests-oauthlib==1.3.0
retrying==1.3.3
rsa==4.0
s3transfer==0.3.3
sacremoses==0.0.35
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.4.1
seaborn==0.10.0
Send2Trash==1.5.0
sentencepiece==0.1.85
six==1.14.0
sklearn==0.0
smmap==3.0.2
tb-nightly==2.3.0a20200422
tensorboard==2.1.1
tensorboard-plugin-wit==1.6.0.post3
tensorboardX==2.0
tensorflow-estimator==2.1.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tf-estimator-nightly==2.3.0.dev2020042201
tf-nightly==2.2.0.dev20200422
tokenizers==0.7.0rc5
torch==1.4.0
torchvision==0.5.0
tornado==6.0.4
tqdm==4.45.0
traitlets==4.3.3
transformers==2.8.0
urllib3==1.25.8
wcwidth==0.1.9
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
zipp==3.1.0

**Comment by balakhonoff** [comment]
Ubuntu 18.04
4 GPU: GTX 1080Ti
