### ISSUE TITLE
Custom collate_fn doesn't work in distributed environment

### ISSUE THREAD

**Issue by vinnamkim** [catalyst-team/catalyst#833]
## 🐛 Bug Report
If `distributed=True`, custom `collate_fn` for `DataLoader` turns into `default_collate`.

### How To Reproduce
1. Train `SupervisedRunner` with custom `collate_fn` and `distributed=True`.
```
runner.train(
    model=model,
    criterion=criterion,
    optimizer=optimizer,
    scheduler=scheduler,
    datasets={
        'batch_size': 24,
        'num_workers': 8,
        'get_datasets_fn': get_datasets,
        'loaders_params': {
            'train': {
                'collate_fn': data_collector.collate_batch
            },
            'valid': {
                'collate_fn': data_collector.collate_batch
            }
        }
    },
    fp16=True,
    distributed=True,
)
```
2. Get error msg
```
Traceback (most recent call last):
  File "train_mlm.py", line 92, in <module>
    runner.train(
  File "/home/kl_reasoning/vinnamkim/catalyst/catalyst/dl/runner/core.py", line 156, in train
    utils.distributed_cmd_run(self.run_experiment, distributed)
  File "/home/kl_reasoning/vinnamkim/catalyst/catalyst/utils/scripts.py", line 137, in distributed_cmd_run
    worker_fn(*args, **kwargs)
  File "/home/kl_reasoning/vinnamkim/catalyst/catalyst/core/runner.py", line 525, in run_experiment
    self._run_event("on_exception")
  File "/home/kl_reasoning/vinnamkim/catalyst/catalyst/core/runner.py", line 330, in _run_event
    getattr(callback, event)(self.state)
  File "/home/kl_reasoning/vinnamkim/catalyst/catalyst/core/callbacks/exception.py", line 20, in on_exception
    raise exception
  File "/home/kl_reasoning/vinnamkim/catalyst/catalyst/core/runner.py", line 512, in run_experiment
    self._run_stage(stage)
  File "/home/kl_reasoning/vinnamkim/catalyst/catalyst/core/runner.py", line 488, in _run_stage
    self._run_epoch(stage=stage, epoch=state.epoch)
  File "/home/kl_reasoning/vinnamkim/catalyst/catalyst/core/runner.py", line 465, in _run_epoch
    self._run_loader(loader)
  File "/home/kl_reasoning/vinnamkim/catalyst/catalyst/core/runner.py", line 399, in _run_loader
    for i, batch in enumerate(loader):
  File "/home/kl_reasoning/swjang90/anaconda3/envs/vinnamkim/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/kl_reasoning/swjang90/anaconda3/envs/vinnamkim/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/kl_reasoning/swjang90/anaconda3/envs/vinnamkim/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/kl_reasoning/swjang90/anaconda3/envs/vinnamkim/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/kl_reasoning/swjang90/anaconda3/envs/vinnamkim/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kl_reasoning/swjang90/anaconda3/envs/vinnamkim/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/kl_reasoning/swjang90/anaconda3/envs/vinnamkim/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
  File "/home/kl_reasoning/swjang90/anaconda3/envs/vinnamkim/lib/python3.8/site-packages/apex/amp/wrap.py", line 81, in wrapper
    return orig_fn(seq, *args, **kwargs)
RuntimeError: stack expects each tensor to be equal size, but got [495] at entry 0 and [178] at entry 1
```

### Environment
Catalyst version: 20.05.1
PyTorch version: 1.5.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1
TensorFlow version: 2.2.0-rc2
TensorBoard version: 2.2.0
OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.13.3
Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.1.168
Nvidia driver version: 418.116.00
cuDNN version: Could not collect

### Additional context
This is happened by the comment when forcing to make distributed loader. Is there any reason not to pass `loader.collate_fn` for distributed loader?

https://github.com/catalyst-team/catalyst/blob/d1d8f4d30cefeaeaac3f4dcb50242fd1f72e82c8/catalyst/core/utils/data.py#L36

**Comment by Scitator** [comment]
Hi,
could you please check the following example with your `collate_fn`?

```python
import os

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset

from catalyst import dl, utils


class Projector(nn.Module):
    def __init__(self, input_size: int):
        super().__init__()
        self.linear = nn.Linear(input_size, 1)

    def forward(self, X: torch.Tensor) -> torch.Tensor:
        return self.linear(X).squeeze(-1)


def datasets_fn(num_features: int):
    """
    Datasets closure.

    Args:
        num_features: number of features for dataset creation.
    """
    X = torch.rand(int(1e4), num_features)
    y = torch.rand(X.shape[0])
    dataset = TensorDataset(X, y)
    # <--- here is the trick --->
    return {
        "train": {"dataset": dataset, "collate_fn": data_collector.collate_batch}, 
        "valid": {"dataset": dataset, "collate_fn": data_collector.collate_batch}, 
    }


def train():
    num_features = 10
    model = Projector(num_features)

    runner = dl.SupervisedRunner()
    runner.train(
        model=model,
        datasets={
            "batch_size": 32,
            "num_workers": 1,
            "get_datasets_fn": datasets_fn,
            "num_features": num_features,
        },
        criterion=nn.MSELoss(),
        optimizer=optim.Adam(model.parameters()),
        logdir="logs/log_example",
        num_epochs=10,
        verbose=True,
        check=True,
        fp16=False,
        distributed=False, 
    )


def main():
    utils.distributed_cmd_run(train)


if __name__ == "__main__":
    main()
```

We already have correct data trasferring to distributed setup here,
https://github.com/catalyst-team/catalyst/blob/master/catalyst/core/utils/data.py#L175#L180

Nevertheless, I am not sure on correct work with `loader_params` and `datasets` simultaneously.

**Comment by vinnamkim** [comment]
@Scitator

The following code works.

```
import os

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset

from catalyst import dl, utils


class Projector(nn.Module):
    def __init__(self, input_size: int):
        super().__init__()
        self.linear = nn.Linear(input_size, 1)

    def forward(self, X: torch.Tensor) -> torch.Tensor:
        return self.linear(X).squeeze(-1)


def datasets_fn(num_features: int):
    """
    Datasets closure.

    Args:
        num_features: number of features for dataset creation.
    """
    X = torch.rand(int(1e4), num_features)
    y = torch.rand(X.shape[0])
    dataset = TensorDataset(X, y)
    # <--- here is the trick --->
    def collate_fn(batch):
        X, y = zip(*batch)
        return torch.stack(X), torch.stack(y)
    return {
        "train": {"dataset": dataset, "collate_fn": collate_fn}, 
        "valid": {"dataset": dataset, "collate_fn": collate_fn}, 
    }


def train():
    num_features = 10
    model = Projector(num_features)

    runner = dl.SupervisedRunner()
    runner.train(
        model=model,
        datasets={
            "batch_size": 32,
            "num_workers": 1,
            "get_datasets_fn": datasets_fn,
            "num_features": num_features,
        },
        criterion=nn.MSELoss(),
        optimizer=optim.Adam(model.parameters()),
        logdir="logs/log_example",
        num_epochs=10,
        verbose=True,
        check=False,
        fp16=False,
        distributed=False, 
    )


def main():
    utils.distributed_cmd_run(train)


if __name__ == "__main__":
    main()
```

But, the setting I reported likes as follows(`distributed=True` in `runner.train`).

```
import os

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset

from catalyst import dl, utils


class Projector(nn.Module):
    def __init__(self, input_size: int):
        super().__init__()
        self.linear = nn.Linear(input_size, 1)

    def forward(self, X: torch.Tensor) -> torch.Tensor:
        return self.linear(X).squeeze(-1)


def datasets_fn(num_features: int):
    """
    Datasets closure.

    Args:
        num_features: number of features for dataset creation.
    """
    X = torch.rand(int(1e4), num_features)
    y = torch.rand(X.shape[0])
    dataset = TensorDataset(X, y)
    # <--- here is the trick --->
    def collate_fn(batch):
        X, y = zip(*batch)
        return torch.stack(X), torch.stack(y)
    return {
        "train": {"dataset": dataset, "collate_fn": collate_fn}, 
        "valid": {"dataset": dataset, "collate_fn": collate_fn}, 
    }


def train():
    num_features = 10
    model = Projector(num_features)

    runner = dl.SupervisedRunner()
    runner.train(
        model=model,
        datasets={
            "batch_size": 32,
            "num_workers": 1,
            "get_datasets_fn": datasets_fn,
            "num_features": num_features,
        },
        criterion=nn.MSELoss(),
        optimizer=optim.Adam(model.parameters()),
        logdir="logs/log_example",
        num_epochs=10,
        verbose=True,
        check=False,
        fp16=False,
        distributed=True, 
    )


def main():
    #utils.distributed_cmd_run(train)
    train()


if __name__ == "__main__":
    main()
```

In that setting, logger says 
```
/home/kl_reasoning/vinnamkim/catalyst/catalyst/core/utils/data.py:62: UserWarning:

With distributed training setup, you need ``DistributedSampler`` for your ``DataLoader``.Transferring to distributed mode. (Experimental feature)
```

It seems It goes into warning of `validate_loaders` in that setting.
https://github.com/catalyst-team/catalyst/blob/9f97ad91c82322a18ac6a5764aaded7fc54720a4/catalyst/core/utils/data.py#L62

**Comment by Scitator** [comment]
🤔  interesting, thanks for noting. 
Generally speaking, `distributed=True` is not our best practice, you can read about it [here](https://catalyst-team.github.io/catalyst/info/distributed.html).
Nevertheless, `collate_fn` issue stills looks like a bug. So, what do you think about such first contribution? I think, it would be more valuable in term of framework development :)

**Comment by Scitator** [comment]
@vinnamkim Hi, have you managed to resolve the issue? would to like to make a PR for everyone?)

**Comment by Scitator** [comment]
@vinnamkim 👀

**Comment by pandov** [comment]
Hello everyone! I think I was able to solve the problem of forced **collate_fn=default_collate_fn** as follows.
Go to file **catalyst/utils/loaders.py** and uncomment the line in **_force_make_distributed_loader**:
```python
loader = DataLoader(
    dataset=copy(loader.dataset),
    batch_size=loader.batch_size,
    # shuffle=loader.shuffle,
    sampler=sampler,
    # batch_sampler=loader.batch_sampler,
    num_workers=loader.num_workers,
    # collate_fn=loader.collate_fn, # <-- this one
    pin_memory=loader.pin_memory,
    drop_last=loader.drop_last,
)
```

**Comment by DavidWiesner** [comment]
I also had this problem. This was my initial setup:
```python
def create_loader(data_source, batch_size, num_classes):
    aug_collations = [v2.CutMix(num_classes=num_classes), v2.MixUp(num_classes=num_classes)]
    random_collations = v2.RandomChoice(aug_collations)

    def collate_fn(batch):
        return random_collations(*default_collate(batch))

    return torch_data.DataLoader(
        data_source,
        batch_size=batch_size,
        collate_fn=collate_fn
    )
```

The problem is that every object that should be used in distributed environment, must be cloned to all its child process and therefore need to be serializable (in python pickle). My solution was to create an callable-Object for the collate_fn:

```python
class BaseDefaultCollate(object):

    def __init__(self, transform) -> None:
        super().__init__()
        self.transform = transform

    def __call__(self, batch):
        return self.transform(*default_collate(batch))

def create_loader(data_source, batch_size, num_classes):
    aug_collations = [v2.CutMix(num_classes=num_classes), v2.MixUp(num_classes=num_classes)]
    random_collations = v2.RandomChoice(aug_collations)

    collate_fn = BaseDefaultCollate(random_collations)

    return torch_data.DataLoader(
        data_source,
        batch_size=batch_size,
        collate_fn=collate_fn
    )
```
