### ISSUE TITLE
Null pointer exception in callbacks/logging.py

### ISSUE THREAD

**Issue by atemate** [catalyst-team/catalyst#931]
## 🐛 Bug Report

```
17/100 * Epoch 17 (train): loss=0.1250
17/100 * Epoch 17 (valid): cmc01=0.5526
^CTraceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 975, in run_experiment
    self._run_stage(stage)
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 944, in _run_stage
    self._run_event("on_epoch_end")
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 780, in _run_event
    getattr(callback, event)(self)
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/callbacks/checkpoint.py", line 604, in on_epoch_end
    minimize_metric=runner.minimize_metric,
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/callbacks/checkpoint.py", line 489, in process_checkpoint
    is_last=True,
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/callbacks/checkpoint.py", line 458, in _save_checkpoint
    saver_fn=self._save_fn,
  File "/opt/conda/lib/python3.7/site-packages/catalyst/utils/checkpoint.py", line 120, in save_checkpoint
    shutil.copyfile(filename, f"{logdir}/last{special_suffix}.pth")
  File "/opt/conda/lib/python3.7/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/modules/ml_train.py", line 69, in <module>
    main(params)
  File "/project/modules/ml_train.py", line 55, in main
    logdir=str(params.dump_dir / params.experiment_name)
  File "/opt/conda/lib/python3.7/site-packages/catalyst/dl/runner/runner.py", line 163, in train
    utils.distributed_cmd_run(self.run_experiment, distributed)
  File "/opt/conda/lib/python3.7/site-packages/catalyst/utils/scripts.py", line 132, in distributed_cmd_run
    worker_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 987, in run_experiment
    self._run_event("on_exception")
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/runner.py", line 780, in _run_event
    getattr(callback, event)(self)
  File "/opt/conda/lib/python3.7/site-packages/catalyst/core/callbacks/logging.py", line 96, in on_exception
    self.tqdm.write("Early exiting")
AttributeError: 'NoneType' object has no attribute 'write'
```

Possibly this line
https://github.com/catalyst-team/catalyst/blob/c8f058f0792f549695227d2a6768b5ce05a4a9ba/catalyst/core/callbacks/logging.py#L96
was executed after this line
https://github.com/catalyst-team/catalyst/blob/c8f058f0792f549695227d2a6768b5ce05a4a9ba/catalyst/core/callbacks/logging.py#L75

**Comment by Scitator** [comment]
Hi @yartem 
Thanks for pointing this out, nice catch!
Would you like to make a small PR hotfix as issue author (it seems like you already found the solution ;) )
I think, something like
```
if self.tqdm is not None:
  self.tqdm.write("Early exiting")
```
should close the issue. What do you think?

**Comment by Scitator** [comment]
btw, fixed in our last update :)
