### ISSUE TITLE
Multi-GPU train error

### ISSUE THREAD

**Issue by adriangrepo** [catalyst-team/catalyst#946]
Similar to closed issue #334.

torch: 1.6.0, catalyst: 20.09.1, Ubuntu 18.04, cuda toolkit 10.2

On running the classification-tutorial.ipynb on local machine runs fine with 1 GPU, but with multiple GPU's get the following error:

```
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/me/miniconda3/envs/catalyst/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/me/miniconda3/envs/catalyst/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/me/miniconda3/envs/catalyst/lib/python3.8/site-packages/pretrainedmodels/models/torchvision_models.py", line 340, in forward
    x = self.features(input)
  File "/home/me/miniconda3/envs/catalyst/lib/python3.8/site-packages/pretrainedmodels/models/torchvision_models.py", line 322, in features
    x = self.conv1(input)
  File "/home/me/miniconda3/envs/catalyst/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/me/miniconda3/envs/catalyst/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/home/me/miniconda3/envs/catalyst/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 415, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)

```

Setup:
```
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"  
torch.cuda.device_count()
->2
```

I dont have a colab paid account to test multi-gpu option on colab.

The following tests wotk fine with multi-GPU's:

```
USE_APEX="1" USE_DDP="1" CUDA_VISIBLE_DEVICES="0,1"     bash ./bin/tests/check_dl_core_.sh
```

I can confirm that multi-gpu also works OK with pytorch-lightning on this machine. 

Any ideas to help debug this?

**Comment by adriangrepo** [comment]
After reading the docs here: https://catalyst-team.github.io/catalyst/info/distributed.html  :-) I got the classification-tutorial.ipynb to work by:

Exporting the notebook as a .py file
Changed:

```
runner = SupervisedRunner(device=device)
```

to

```
runner = SupervisedRunner()
```

and then to the runner.train call added

```
distributed=True,
```

Now working fine on 3 GPU's
